### ISSUE TITLE
Använd model-basklass för att interagera med databas

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [ITGGOT-Emanuel-Swenson/chllnge#6]
t.ex `User.get(username: username)`

https://github.com/ITGGOT-Emanuel-Swenson/chllnge/blob/554f23c045849d4be32f10860608a649e05cbc85/models/models.rb#L8

**Comment by ITGGOT-Emanuel-Swenson** [comment]
utfört

**Comment by ntijoh-daniel-berg** [comment]
Du får gärna stänga dina issues via dina commit messages så kan jag lätt se _hur_ du löst det.
